Assignment.CustomerSite/Models/ErrorViewModel.cs
using System;

namespace Assignment.CustomerSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment.CustomerSite/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.CustomerSite.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "oidc");
        }

        public new IActionResult SignOut()
        {
            return SignOut(new AuthenticationProperties { RedirectUri = "/" }, "Cookies", "oidc");
        }

        [Authorize]
        public ActionResult MyProfile()
        {
            return View();
        }
    }
}

Assignment.CustomerSite/Controllers/HomeController.cs
using Assignment.CustomerSite.Models;
using Assignment.CustomerSite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.CustomerSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICategoryApiClient _cateApiClient;
        private readonly IProductApiClient _productApiClient;
        public HomeController(ILogger<HomeController> logger, ICategoryApiClient cateApiClient, IProductApiClient productApiClient)
        {
            _logger = logger;
            _cateApiClient = cateApiClient;
            _productApiClient = productApiClient;
        }

        public async Task<IActionResult> Index()
        {
            var cate = await _cateApiClient.GetCategory();
            var product = await _productApiClient.GetProducts();
            var productCate = await _productApiClient.GetProductByCate(2);
            var productCate1 = await _productApiClient.GetProductByCate(1);
            ViewBag.ProductCate = productCate;
            ViewBag.ProductCate1 = productCate1;
            ViewBag.Product = product;
            ViewBag.Cate = cate;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignment.CustomerSite/Controllers/ProductController.cs
using Assignment.CustomerSite.Services;
using Assignment.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.CustomerSite.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        public ProductController(IProductApiClient productApiClient)
        {
            _productApiClient = productApiClient;
        }
        public async Task<IActionResult> Index(int id)
        {
            var productCate = await _productApiClient.GetProductByCate(id);
            ViewBag.ProductCate = productCate;
            return View();
        }
        public async Task<IActionResult> Detail(string id)
        {
            var product = await _productApiClient.GetProductByID(id);
            var rate = await _productApiClient.GetRating(id);
                    ViewBag.rate = rate;
            ViewBag.rateCount = rate.Count();
            ViewBag.Product = id;
            return View(product);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostReview(int rate, string comments, string productId)
        {
            var review = new RatingRequest
            {
                
                Comments = comments,
                Rate = rate,
                ProductId = productId
            };

            await _productApiClient.PostRating(review);

            return RedirectToAction("Detail", new { id = productId });
        }

        public async Task<IActionResult> ShowProductByCate(int idCate)
        {

            var product = await _productApiClient.GetProductByCate(idCate);
            return View(product);
        }
    }
}

Assignment.CustomerSite/ViewComponents/CategoryMenuViewComponent.cs
using Assignment.CustomerSite.Services;
using Assignment.Shared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.CustomerSite.ViewComponents
{
    public class CategoryMenuViewComponent: ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoryMenuViewComponent(ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cate = await _categoryApiClient.GetCategory();
            return View(cate);
        }
    }
}

Assignment.CustomerSite/ViewComponents/ProductViewComponent.cs
using Assignment.Shared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.CustomerSite.ViewComponents
{
    public class ProductViewComponent: ViewComponent
    {
       public async Task<IViewComponentResult> InvokeAsync(ProductRespone respone)
        {
            return await Task.FromResult(View("Default", respone));
        }
    }
}

Assignment.CustomerSite/ViewComponents/RatingViewComponent.cs
using Assignment.Shared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.CustomerSite.ViewComponents
{
    public class RatingViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(RatingRespone review)
        {
            return View("Default", review);
        }
    }
}

Assignment.CustomerSite/ViewComponents/RelatedProductViewComponent.cs
using Assignment.Shared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.CustomerSite.ViewComponents
{
    public class RelatedProductViewComponent: ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(ProductRespone respone)
        {
            return await Task.FromResult(View("Default", respone));
        }
    }
}

Assignment.CustomerSite/Views/Home/Index.cshtml
@model IEnumerable<Assignment.Shared.ProductRespone>
@{
    ViewData["Title"] = "Home Page";
}


<div class="single-product-slider mt-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <div class="section-title">
                    <h1>Our Products Ralated</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- single product -->
            @foreach (var item in ViewBag.ProductCate)
            {

                @await Component.InvokeAsync("RelatedProduct", item);
            }
        </div>
        <div class="row">
            <!-- single product -->
            @foreach (var item in ViewBag.ProductCate1)
            {
                @await Component.InvokeAsync("RelatedProduct", item);
            }
        </div>
    </div>
</div>

<div class="single-product-slider mt-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <div class="section-title">
                    <h1>Our Products</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- single product -->
            @foreach (var item in ViewBag.Product)
            {
                @await Component.InvokeAsync("Product", item)
            }
        </div>
    </div>
</div>

Assignment.CustomerSite/Views/Product/Detail.cshtml
@model ProductRespone
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <a asp-controller="Product" asp-action="Detail" asp-route-id="@Model.ProductId"><img class="img-fluid" src="@Model.ProductImg" alt="@Model.NameProduct"></a>
        </div>
        <div class="col-lg-5 offset-lg-1">
            <div class="s_product_text">
                <h3>@Model.NameProduct</h3>
                <h2>@Convert.ToDecimal(Model.Price).ToString("#,##") $</h2>
                <ul class="list">
                    <li><a class="active" href="#"><span>Category</span> : @Model.NameCategory</a></li>
                    <li><a href="#"><span>Availibility</span> : In Stock</a></li>
                </ul>
                <p>
                    @Model.Description
                </p>
                <div class="card_area d-flex align-items-center">
                    <a class="primary-btn" href="#">Add to Cart</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="review_box">
            <h4>Add a Review</h4>
            <p>Your Rating:</p>
            <h3>
                @for (int i = 0; i < Model.Rate; i++)
                {
                    <i class="ion-android-star" style="color: #ffdd59"></i>
                }
            </h3>
            <h2 class="h3">What do you think? (#@ViewBag.rateCount)</h2>
            <div class="wrapper">
                <div class="content">
                    @foreach (var review in ViewBag.rate)
                    {
                        @await Component.InvokeAsync("Rating", review);
                    }
                </div>
            </div>

            <form class="join" asp-action="PostReview" asp-controller="Product" method="post">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="rate">
                            <input type="radio" id="star5" name="rate" value="5" />
                            <label for="star5" title="text">5 stars</label>
                            <input type="radio" id="star4" name="rate" value="4" />
                            <label for="star4" title="text">4 stars</label>
                            <input type="radio" id="star3" name="rate" value="3" />
                            <label for="star3" title="text">3 stars</label>
                            <input type="radio" id="star2" name="rate" value="2" />
                            <label for="star2" title="text">2 stars</label>
                            <input type="radio" id="star1" name="rate" value="1" />
                            <label for="star1" title="text">1 star</label>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <input type="text" name="userName" value="" placeholder="Name" required class="form-control" />
                        <input type="hidden" name="productId" value="@Model.ProductId" />
                        <br>
                    </div>
                    <div class="col-sm-12">
                        <textarea name="comments" placeholder="Type here" required class="form-control" rows="5"></textarea>
                        <br>
                    </div>
                    <div class="col-sm-12">
                        <div class="align-center">
                            <br>
                            <button type="submit" class="btn btn-primary btn-sm"> <i class="ion-android-send"></i> Send</button>
                            <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal"> <i class="ion-android-share"></i> No, thanks </button>
                            <br><br>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

Assignment.CustomerSite/Views/Product/Index.cshtml
@model Assignment.Shared.CategoryRespone

<div class="container">
    <div class="row">
        @foreach (var cate in ViewBag.ProductCate)
        {
        <div class="col-lg-3 col-md-6">
            <div class="single-product">
                <a asp-controller="Product" asp-action="Detail" asp-route-id="@cate.ProductId"><img class="img-fluid" src="@cate.ProductImg" alt="@cate.NameProduct"></a>
                <div class="product-details">
                    <h6>
                        @cate.NameProduct
                    </h6>
                    <div class="price">
                        <h6>@Convert.ToDecimal(cate.Price).ToString("#,##") VND</h6>
                    </div>
                    <p>@cate.Description</p>
                    <div class="prd-bottom">

                        <a href="" class="social-info">
                            <span class="ti-bag"></span>
                            <p class="hover-text">add to bag</p>
                        </a>
                        <a href="" class="social-info">
                            <span class="lnr lnr-heart"></span>
                            <p class="hover-text">Wishlist</p>
                        </a>
                        <a href="" class="social-info">
                            <span class="lnr lnr-sync"></span>
                            <p class="hover-text">compare</p>
                        </a>
                        <a href="" class="social-info">
                            <span class="lnr lnr-move"></span>
                            <p class="hover-text">view more</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        }
    </div>
</div>
<br>
<br>

Assignment.CustomerSite/Views/Product/ShowProductByCate.cshtml
@model Assignment.Shared.ProductRespone


<div class="col-lg-3 col-md-6">
    <div class="single-product">
        <a asp-controller="Product" asp-action="ShowProductByCate" asp-route-id="@Model.ProductId"><img class="img-fluid" src="@Model.ProductImg" alt="@Model.NameProduct"></a>
        <div class="product-details">
            <h6>
                @Model.NameProduct
            </h6>
            <h6>
                @Model.NameCategory
            </h6>
            <h6>
                @Model.CategoryID
            </h6>
            <div class="price">
                <h6>@Convert.ToDecimal(Model.Price).ToString("#,##") VND</h6>
            </div>
            <p>@Model.Description</p>
            <div class="prd-bottom">

                <a href="" class="social-info">
                    <span class="ti-bag"></span>
                    <p class="hover-text">add to bag</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-heart"></span>
                    <p class="hover-text">Wishlist</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-sync"></span>
                    <p class="hover-text">compare</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-move"></span>
                    <p class="hover-text">view more</p>
                </a>
            </div>
        </div>
    </div>
</div>

Assignment.CustomerSite/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Assignment.Shared.CategoryRespone>

@foreach (var cate in Model)
{
    <li class="nav-item"><a class="nav-link" asp-controller="Product" asp-action="Index" asp-route-id="@cate.CategoryId">@cate.Name</a></li>
}

Assignment.CustomerSite/Views/Shared/Components/Product/Default.cshtml
@model Assignment.Shared.ProductRespone;


<div class="col-lg-3 col-md-6">
    <div class="single-product">
        <a asp-controller="Product" asp-action="Detail" asp-route-id="@Model.ProductId"><img class="img-fluid" src="@Model.ProductImg" alt="@Model.NameProduct"></a>
        <div class="product-details">
            <h6>
                @Model.NameProduct
            </h6>
            <p>
                @for (int i = 0; i < Model.Rate; i++)
                {
                    <i class="ion-android-star" style="color: #ffdd59"></i>
                }
            </p>
            <div class="price">
                <h6>@Convert.ToDecimal(Model.Price).ToString("#,##") VND</h6>
            </div>
            <p>@Model.Description</p>
            <div class="prd-bottom">

                <a href="" class="social-info">
                    <span class="ti-bag"></span>
                    <p class="hover-text">add to bag</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-heart"></span>
                    <p class="hover-text">Wishlist</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-sync"></span>
                    <p class="hover-text">compare</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-move"></span>
                    <p class="hover-text">view more</p>
                </a>
            </div>
        </div>
    </div>
</div> 

Assignment.CustomerSite/Views/Shared/Components/Rating/Default.cshtml
@model Assignment.Shared.RatingRespone

<h3>
    @for (int i = 0; i < Model.Rate; i++)
    {
        <i class="fas fa-star" style="color: #ffdd59"></i>
    }
</h3>
<label>@Convert.ToDateTime(Model.PublishDate).ToString("dd-MM-yyyy")</label>
<p>@Model.Comments</p>

Assignment.CustomerSite/Views/Shared/Components/RelatedProduct/Default.cshtml
@model Assignment.Shared.ProductRespone;



<div class="col-lg-3 col-md-6">
    <div class="single-product">
        <a asp-controller="Product" asp-action="Detail" asp-route-id="@Model.ProductId"><img class="img-fluid" src="@Model.ProductImg" alt="@Model.NameProduct"></a>
        <div class="product-details">
            <h6>
                @Model.NameProduct
            </h6>
            <h6>
                @Model.NameCategory
            </h6>
            <div class="price">
                <h6>@Convert.ToDecimal(Model.Price).ToString("#,##") VND</h6>
            </div>
            <p>@Model.Description</p>
            <div class="prd-bottom">

                <a href="" class="social-info">
                    <span class="ti-bag"></span>
                    <p class="hover-text">add to bag</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-heart"></span>
                    <p class="hover-text">Wishlist</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-sync"></span>
                    <p class="hover-text">compare</p>
                </a>
                <a href="" class="social-info">
                    <span class="lnr lnr-move"></span>
                    <p class="hover-text">view more</p>
                </a>
            </div>
        </div>
    </div>
</div>

Assignment.CustomerSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="img/fav.png">
    <meta name="author" content="CodePixar">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>@ViewData["Title"] Assignment - CustomerSite</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/nouislider.min.css">
    <link rel="stylesheet" href="~/css/ion.rangeSlider.css" />
    <link rel="stylesheet" href="~/css/ion.rangeSlider.skinFlat.css" />
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/main.css">
    <link href="~/css/Rating.css" rel="stylesheet">
</head>
<body>
    <header class="header_area sticky-header">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light main_box">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar-brand logo_h" href="index.html"><img src="~/img/logo.png" alt=""></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item active"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="nav-item submenu dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">Shop</a>
                                <ul class="dropdown-menu">
                                    @await Component.InvokeAsync("CategoryMenu")
                                </ul>
                            </li>
                            <partial name="_LoginPartial" />
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item"><a href="#" class="cart"><span class="ti-bag"></span></a></li>
                            <li class="nav-item">
                                <button class="search"><span class="lnr lnr-magnifier" id="search" onclick="myClick()"></span></button>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="search_input" id="search_input_box" style="display:none">
            <div class="container">
                <form class="d-flex justify-content-between">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                </form>
            </div>
        </div>
    </header>

    <div class="container pt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Us</h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
                            magna aliqua.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>Stay update with our latest</p>
                        <div class="" id="mc_embed_signup">

                            <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                  method="get" class="form-inline">

                                <div class="d-flex flex-row">

                                    <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                           required="" type="email">


                                    <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                    <div style="position: absolute; left: -5000px;">
                                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                    </div>
                                </div>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Follow Us</h6>
                        <p>Let us be social</p>
                        <div class="footer-social d-flex align-items-center">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
                <p class="footer-text m-0">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                </p>
            </div>
        </div>
    </footer>
    <script src="~/lib/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="~/lib/js/vendor/bootstrap.min.js"></script>
    <script src="~/lib/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/lib/js/jquery.nice-select.min.js"></script>
    <script src="~/lib/js/jquery.sticky.js"></script>
    <script src="~/lib/js/nouislider.min.js"></script>
    <script src="~/lib/js/countdown.js"></script>
    <script src="~/lib/js/jquery.magnific-popup.min.js"></script>
    <script src="~/lib/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/Template/assets/js/jquery.ui.touch-punch.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        function myClick() {
            var x = document.getElementById("search_input_box");
            if (window.getComputedStyle(x).display === "none") {
                x.style.display = "block";
            }
            else {
                x.style.display = "none";
            }
        }
    </script>
</body>
</html>